import{a as q,S as E,i as c}from"./assets/vendor-hwdYKDic.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const S="48830775-40ff68ea61f2bc47ba43ee541",v="https://pixabay.com/api/",P=40;async function g(r,e){const i=`${v}?key=${S}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=${P}`;try{return(await q.get(i)).data}catch(n){throw console.error("Error fetching data from Pixabay API:",n),n}}function f(r,e=!1){const i=document.querySelector("#gallery");e&&(i.innerHTML="");const n=r.map(({largeImageURL:o,webformatURL:l,tags:h,likes:y,views:L,comments:w,downloads:b})=>`
      <a href="${o}" class="gallery-item">
        <img src="${l}" alt="${h}" />
        <div class="image-info">
          <p><strong>Likes:</strong> ${y}</p>
          <p><strong>Views:</strong> ${L}</p>
          <p><strong>Comments:</strong> ${w}</p>
          <p><strong>Downloads:</strong> ${b}</p>
        </div>
      </a>`).join("");i.insertAdjacentHTML("beforeend",n),new E(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1}).refresh()}function $(){var e;const r=((e=document.querySelector(".gallery-item"))==null?void 0:e.getBoundingClientRect().height)||100;window.scrollBy({top:r*2,behavior:"smooth"})}const a={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery"),loadMoreBtn:document.querySelector(".more-btn")},s={query:"",page:1,totalHits:0};function p(){a.loader.classList.remove("hidden")}function d(){a.loader.classList.add("hidden")}function m(){a.loadMoreBtn.classList.remove("hidden")}function u(){a.loadMoreBtn.classList.add("hidden")}a.form.addEventListener("submit",async r=>{if(r.preventDefault(),s.query=a.input.value.trim(),s.page=1,!s.query){c.error({title:"Error",message:"Please enter a search term!",position:"topRight",timeout:2e3});return}p(),u();try{const{hits:e,totalHits:i}=await g(s.query,s.page);s.totalHits=i,d(),e.length===0?c.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}):(f(e,!0),e.length<s.totalHits&&m())}catch(e){d(),c.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",e)}});a.loadMoreBtn.addEventListener("click",async()=>{s.page+=1,u(),p();try{const{hits:r}=await g(s.query,s.page);d(),m(),r.length===0?(u(),c.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):(f(r),$(),s.page*40>=s.totalHits&&(u(),c.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})))}catch(r){d(),c.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",r)}});
//# sourceMappingURL=index.js.map
